# Generated by Django 4.2.6 on 2023-10-15 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_activationcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activationcode',
            old_name='code',
            new_name='token',
        ),
        migrations.AddField(
            model_name='activationcode',
            name='uid',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
